src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

src/rsvp/urls.py
from django.conf.urls import patterns, url

from .views import rsvp, person, song

urlpatterns = [
    url(r'^$', rsvp, name='rsvp'),
    url(r'^song/$', song, name='song'),
    url(r'^person/(?P<name>.*)$', person, name='person'),
    #url(r'^group$', group, name='group'),
]

src/wedding/urls.py
import autocomplete_light
autocomplete_light.autodiscover()

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import rsvp.urls
from . import views


urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^registry/$', views.RegistryPage.as_view(), name='registry'),
    url(r'^wedding/$', views.WeddingPage.as_view(), name='wedding'),
    url(r'^logistics/$', views.LogisticsPage.as_view(), name='logistics'),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^rsvp/', include(rsvp.urls, namespace='rsvp')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^static/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/wedding/views.py
from django.shortcuts import render
from django.views import generic
import math
from collections import OrderedDict
from rsvp.models import LifeEvent, WeddingEvent, Logistics

# Create your views here.


class HomePage(generic.View):
    template_name = "home.html"

    def get(self, request, *args, **kwargs):
        events = LifeEvent.objects.all()
        return render(request, self.template_name, {'events': events})


class RegistryPage(generic.TemplateView):
    template_name = "registry.html"


class WeddingPage(generic.TemplateView):
    template_name = "wedding.html"

    def get(self, request, *args, **kwargs):
        """
        Seprates the events into a dict with keys of dates and values as lists
        that contain the events that start during that date.
        """
        events = WeddingEvent.objects.all()
        days = OrderedDict()
        for event in events:
            days.setdefault(event.event_start.date(), []).append(event)
            if event.main_event:
                main_event = event
        col_size = 3 if len(days) == 4 else None  # 4 days is 3 col
        col_size = 4 if col_size else 6  # 3 days is 4 col, 2 days is 6 col
        return render(request, self.template_name, {
            'events': events,
            'days': days,
            'col_size': col_size,
            'main_event': main_event,
        })


class LogisticsPage(generic.TemplateView):
    template_name = "logistics.html"

    def get(self, request, *args, **kwargs):
        travels = Logistics.objects.filter(section='travel')
        hotels = Logistics.objects.filter(section='hotel')
        outings = Logistics.objects.filter(section='outing')
        return render(request, self.template_name, {
            'travels': travels,
            'hotels': hotels,
            'outings': outings,
        })

src/templates/_brandname.html
Mike and Zoey's Wedding

src/templates/_navbar.html
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
<li {% if active_link == "wedding" %}class="active"{% endif %}><a href="{% url 'wedding' %}">Wedding</a></li>
<li {% if active_link == "logistics" %}class="active"{% endif %}><a href="{% url 'logistics' %}">Logistics</a></li>
<li {% if active_link == "registry" %}class="active"{% endif %}><a href="{% url 'registry' %}">Wedding Registry</a></li>
<li {% if active_link == "rsvp" %}class="active"{% endif %}><a href="{% url 'rsvp:rsvp' %}">RSVP</a></li>

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    {% load i18n %}
    
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    <link href="{% static 'site/css/site.css' %}" rel="stylesheet">
    <link href="{% static 'site/css/notifIt.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    {% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static 'site/img/logo.png' %}" alt="logo">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
			<img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
			{{ user.get_full_name|truncatechars:20 }}
			<span class="caret"></span>
		    </a>
		    
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
                </li>
              {% endif %}
            {% endblock %}
          </ul>
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
    
    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <a name="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; <a href="https://handycodejob.com/">HandyCodeJob LLC</a> {% now 'Y' %}</p>
          </div>
          <div class="col-lg-6 text-right">
            Connect with Mike
            <a href="https://www.facebook.com/mikeyh"><i class="fa fa-facebook"></i> Facebook</a>
            <a href="https://twitter.com/mikehenry42"><i class="fa fa-twitter"></i> Twitter</a>
            <a href="https://instagram.com/mikemhenry/"><i class="fa fa-instagram"></i> Instagram</a>
          </div>
          <div class="col-lg-6 text-right">
            Connect with Zoey
            <a href="https://www.facebook.com/brittany.zoey.hogue"><i class="fa fa-facebook"></i> Facebook</a>
            <a href="https://twitter.com/ZoeyHogue"><i class="fa fa-twitter"></i> Twitter</a>
            <a href="https://www.pinterest.com/brittanyzoe8/"><i class="fa fa-pinterest"></i> Pinterest</a>
            <a href="https://www.instagram.com/zoeyhogue"><i class="fa fa-instagram"></i> Instagram</a>
          </div>
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'site/js/site.js' %}"></script>
    <script src="{% static 'site/js/notifIt.min.js' %}"></script>
    {% include 'autocomplete_light/static.html' %}
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

src/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block splash %}
  <div class="jumbotron">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center">
          <h1 style="color:#9c27b0;">Mike Henry</h1>
          <h1 style="color:#f44336;">&</h1>
          <h1 style="color:#9c27b0;">Zoey Hogue</h1>
        </div>
        <div class="col-md-8 col-md-offset-2 col-sm-10">
          <ul class="events">
            <div class="text-center">
              <a class="btn btn-primary" href="{% url 'rsvp:rsvp' %}" role="button">RSVP for our Wedding!</a>
            </div>
            {% for event in events %}
            <li class="event">
              <h2 id="{{ event.slug }}"class="event-header">
                <span class="event-title">{{ event.title }}</span>
                <hr class="event-title-hr">
                <b class="event-person" title=""> </b>
              </h2>
              {% if event.picture %}
              <div class="event-photo text-center">
                <img class="img-responsive event-img" src="{{ event.picture.url }}" alt="{{ event.title }}">
              </div>
              {% endif %}
               <div class="event-desc">
                <p class="event-text">
                  {{ event.text }}  
                </p>
                <hr class="event-date-hr">
                <p class="event-date text-right">{{ event.date }}</p>
              </div>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
{% endblock splash %}

{% block container %}
<!-- Benefits of the Django application -->
<a name="about"></a>

<div class="container">
  <div class="row">
  </div>
</div>

{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}

src/templates/logistics.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Logistics{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="logistics" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        {% autoescape off %}
        <ul class="accordion-tabs">
            {% if travels %}
            <li class="tab-header-and-content">
                <a href="javascript:void(0)" class="is-active tab-link">Travel</a>
                <div class="tab-content">
                    {% for entry in travels %}
                      {% if entry.name %}
                        <h3><a class="link" href="{{ entry.website }}">{{ entry.name }}</a></h3>
                      {% elif entry.website %}
                        <h2><a class="link" href="{{ entry.website }}">{ entry.title }}</a></h2>
                      {% else %} 
                        <h2>{{ entry.title }}</h2>
                      {% endif %}
                      <p>{{ entry.description|linebreaks }}</p>
                    {% endfor %}
                </div>
            </li>
            {% endif %}
            {% if hotels %}
            <li class="tab-header-and-content">
                <a href="javascript:void(0)" class="tab-link">Hotels</a>
                <div class="tab-content">
                    {% for entry in hotels %}
                      {% if entry.name %}
                        <h3><a class="link" href="{{ entry.website }}">{{ entry.name }}</a></h3>
                      {% elif entry.website %}
                        <h2><a class="link" href="{{ entry.website }}">{{ entry.title }}</a></h2>
                      {% else %} 
                        <h2>{{ entry.title }}</h2>
                      {% endif %}
                      <p>{{ entry.description|linebreaks }}</p>
                    {% endfor %}
                </div>
            </li>
            {% endif %}
            {% if outings %}
            <li class="tab-header-and-content">
                <a href="javascript:void(0)" class="tab-link">Outings</a>
                <div class="tab-content">
                    {% for entry in outings %}
                      {% if entry.name %}
                        <h3><a class="link" href="{{ entry.website }}">{{ entry.name }}</a></h3>
                      {% elif entry.website %}
                        <h2><a class="link" href="{{ entry.website }}">{ entry.title }}</a></h2>
                      {% else %} 
                        <h2>{{ entry.title }}</h2>
                      {% endif %}
                      <p>{{ entry.description|linebreaks }}</p>
                    {% endfor %}
                </div>
            </li>
            {% endif %}
         </ul>
         {% endautoescape %}
      </div>
    </div>
  </div>
</div>
{% endblock container %}

src/templates/registry.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Wedding Registry{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="registry" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1 style="padding-top: 35px">Wedding Registry</h1>
        <h3>We are registered at Target and Williams-Sonoma</h3>
        <p>Since we are moving to Boise after the wedding, we would prefer items shipped to our Boise address:</p><p style="text-align: left; margin-left: 30%;">
          304 West Bannock St <br>
          Apt 5 <br>
          Boise ID 83702
        </p>
        <div class="row">
          <a href="https://secure.williams-sonoma.com/registry/n5lbfqx7sg/registry-list.html">
            <img style="padding: 15px" src="{% static 'site/img/williams-sonoma-logo.png' %}">
          </a>
        </div>
        <div class="row">
          <a href="http://www.target.com/gift-registry/giftgiver?registryId=cNUVXl24cDZvdLug6Kqa7A&registryType=WEDDING">
              <img style="padding: 15px" src="{% static 'site/img/Target-Logo.png' %}">
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock container %}

src/templates/wedding.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Wedding Events{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="wedding" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row calendar">
      {% for day, list in days.items %}
      {# Use offset if their are only 2 days. We have to only allow the first to have the offset #}
      <div class="col-md-{% if col_size != 6%}{{ col_size }}{% elif forloop.first %}3 col-md-offset-3{% else %}3{% endif %} day">
          <h2>{{ day|date:"M d, Y" }}</h2>
          {% for event in list %}
            <a class="name link"  href="#{{ event.slug }}">{{ event.clean_name }}</a></br>
            <span class="time">{{ event.event_start|date:"P" }} - {{ event.event_end|date:"P" }}</span></br>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
    <div class="row flex">
      <div class="col-md-6 col-md-offset-2 event-loc">
        {% for event in events %}
          {% autoescape off %}
          <h3 id="{{ event.slug }}">{{ event.title }}</h3>
          <p>{{ event.event_note|linebreaks }}</p>
          <a class="link" href="{{ event.location_website }}"><strong>{{ event.location_name }}</strong></a>
          </br>
          <a class="link" href="{{ event.location_map }}">{{ event.location_addr|linebreaks }}</a>
          <p>{{ event.event_description|linebreaks }}</p>
          {% endautoescape %}
          </br>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock container %}